// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/kentr.h"
#include <Rcpp.h>

using namespace Rcpp;

// hamming_distance_iterator
std::vector<int> hamming_distance_iterator(std::string bc_to_test, std::vector< std::string > all_bcs);
RcppExport SEXP kentr_hamming_distance_iterator(SEXP bc_to_testSEXP, SEXP all_bcsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bc_to_test(bc_to_testSEXP);
    Rcpp::traits::input_parameter< std::vector< std::string > >::type all_bcs(all_bcsSEXP);
    rcpp_result_gen = Rcpp::wrap(hamming_distance_iterator(bc_to_test, all_bcs));
    return rcpp_result_gen;
END_RCPP
}
// mismatch_position_calc
std::vector<int> mismatch_position_calc(std::string bc_to_test, std::vector< std::string > all_bcs);
RcppExport SEXP kentr_mismatch_position_calc(SEXP bc_to_testSEXP, SEXP all_bcsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bc_to_test(bc_to_testSEXP);
    Rcpp::traits::input_parameter< std::vector< std::string > >::type all_bcs(all_bcsSEXP);
    rcpp_result_gen = Rcpp::wrap(mismatch_position_calc(bc_to_test, all_bcs));
    return rcpp_result_gen;
END_RCPP
}
