# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compare a string to a vector of strings and report hamming distance
#' @param bc_to_test String to get hamming distance
#' @param all_bcs character vector to compare
#' @export
hamming_distance_iterator <- function(bc_to_test, all_bcs) {
    .Call('kentr_hamming_distance_iterator', PACKAGE = 'kentr', bc_to_test, all_bcs)
}

#' Compare a string to a vector of strings report mismatch position
#' @param bc_to_test String to check
#' @param all_bcs character vector to compare
#' @export
mismatch_position_calc <- function(bc_to_test, all_bcs) {
    .Call('kentr_mismatch_position_calc', PACKAGE = 'kentr', bc_to_test, all_bcs)
}

