# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_bam <- function(bampath) {
    .Call('_kentr_read_bam', PACKAGE = 'kentr', bampath)
}

#' Fetch DNA sequence from an indexed fasta file
#' @param df dataframe wtih columns chrom start and end
#' @param fapath path to indexed fasta file
#' @export
getSeq <- function(df, fapath) {
    .Call('_kentr_getSeq', PACKAGE = 'kentr', df, fapath)
}

#' Reverse complement a vector of DNA sequences
#' @param vec character vector of DNA [ATCGN]
#' @export
revComp <- function(vec) {
    .Call('_kentr_revComp', PACKAGE = 'kentr', vec)
}

#' Compare a string to a vector of strings and report hamming distance
#' @param bc_to_test String to get hamming distance
#' @param all_bcs character vector to compare
#' @export
get_hamming <- function(bc_to_test, all_bcs) {
    .Call('_kentr_get_hamming', PACKAGE = 'kentr', bc_to_test, all_bcs)
}

#' Compare a string to a vector of strings report mismatch position
#' @param bc_to_test String to check
#' @param all_bcs character vector to compare
#' @export
find_mismatch <- function(bc_to_test, all_bcs) {
    .Call('_kentr_find_mismatch', PACKAGE = 'kentr', bc_to_test, all_bcs)
}

